apiVersion: apps/v1
kind: Deployment

metadata:
  name: booking-backend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: booking-backend

  template:
    metadata:
      labels:
        app: booking-backend

    spec:
      containers:
        - name: booking-backend
          image: ajaydhadi95/booking_backend:latest

          ports:
            - containerPort: 82

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

---

apiVersion: v1
kind: Service

metadata:
  name: booking-backend-service

spec:
  type: LoadBalancer

  selector:
    app: booking-backend

  ports:
    - protocol: TCP
      port: 82
      targetPort: 82